# Site settings
title: Tim Roller
description: "Public website, build with Jekyll."
url: "http://TimRoller.github.io/home/"
author:
  name: "Tim Roller"
  email: "timroller@gmail.com"
  url: "http://TimRoller.github.io/home/"

# Build settings
baseurl: /home/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Options
custom_header: false
custom_nav_footer: true
reverse: false
